"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var clasico_1 = require("./clasico");
var moderno_1 = require("./moderno");
var ruleta_1 = require("./ruleta");
var juego3_1 = require("./juego3");
var slot11 = new clasico_1.Clasico(100);
var slot2 = new moderno_1.Moderno(100);
var ruleta = new ruleta_1.Ruleta(9, 50, 0.4);
var poker = new juego3_1.Poker();
// slot11.modo();
// slot11.juego();
// slot11.resultado();
// ruleta.apuesta();
// ruleta.ruleta();
// ruleta.resultado();
// slot2.modo();
// slot2.juego();
// slot2.resultado();
poker.aJugar();
